<a href="https://colab.research.google.com/github/sattvikkk/svm_classifier/blob/main/SVM.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import pickle
import pandas as pd
from sklearn.model_selection import train_test_split
from preprocess1 import *
from sklearn.metrics import accuracy_score

In [4]:
df=pd.read_csv("loan_approved.csv")

In [5]:
df.columns

Index(['Loan_ID', 'Gender', 'Married', 'Dependents', 'Education',
       'Self_Employed', 'ApplicantIncome', 'CoapplicantIncome', 'LoanAmount',
       'Loan_Amount_Term', 'Credit_History', 'Property_Area',
       'Loan_Status (Approved)'],
      dtype='object')

In [6]:
df.isnull().sum()

Loan_ID                    0
Gender                    13
Married                    3
Dependents                15
Education                  0
Self_Employed             32
ApplicantIncome            0
CoapplicantIncome          0
LoanAmount                22
Loan_Amount_Term          14
Credit_History            50
Property_Area              0
Loan_Status (Approved)     0
dtype: int64

In [8]:
df.loc[df.Gender.isnull(),'Gender']="Male"
df.loc[df.Married.isnull(),'Married']="Yes"
df.loc[df.Dependents.isnull(),'Dependents']="0"
df.loc[df.Self_Employed.isnull(),'Self_Employed']="No"
df.loc[df.LoanAmount.isnull(),'LoanAmount']=df.LoanAmount.median()
df.loc[df.Loan_Amount_Term.isnull(),'Loan_Amount_Term']=df.Loan_Amount_Term.median()
df.loc[df.Credit_History.isnull(),'Credit_History']=0.0

In [9]:
df.isnull().sum()

Loan_ID                   0
Gender                    0
Married                   0
Dependents                0
Education                 0
Self_Employed             0
ApplicantIncome           0
CoapplicantIncome         0
LoanAmount                0
Loan_Amount_Term          0
Credit_History            0
Property_Area             0
Loan_Status (Approved)    0
dtype: int64

In [27]:
with open("preprocessing1 (1).pkl","rb") as f:
    preprocessor=pickle.load(f)

In [28]:
preprocessor

ColumnTransformer(transformers=[('OHE columns', OneHotEncoder(),
                                 ['Self_Employed', 'Property_Area', 'Gender']),
                                ('Label_encoder', ModifiedLabelEncoder(),
                                 'Married'),
                                ('standard_scaler', StandardScaler(),
                                 ['ApplicantIncome', 'CoapplicantIncome',
                                  'LoanAmount']),
                                ('custom',
                                 FunctionTransformer(func=<function divide_by_12 at 0x7df9aeab82c0>),
                                 ['Loan_Amount_Term']),
                                ('pass through',
                                 FunctionTransformer(func=<function same at 0x7df978722700>),
                                 ['Credit_History']),
                                ('ordinal dependents',
                                 OrdinalEncoder(categories=[['0', '1', '2',
                                                             '3+']]),
                                 ['Dependents']),
                                ('ordinal education',
                                 OrdinalEncoder(categories=[['Not Graduate',
                                                             'Graduate']]),
                                 ['Education']),
                                ('Label Label encoder', ModifiedLabelEncoder(),
                                 ['Loan_Status (Approved)'])])

In [31]:
train,test,_,_=train_test_split(df,df["LoanAmount"],test_size=0.2,random_state=42)

In [32]:
train['Loan_Status (Approved)'].value_counts()

Loan_Status (Approved)
Y    342
N    149
Name: count, dtype: int64

In [33]:
processed_data=preprocessor.fit_transform(train)

In [34]:
processed_data

array([[1., 0., 0., ..., 0., 1., 0.],
       [1., 0., 0., ..., 0., 1., 1.],
       [1., 0., 0., ..., 2., 1., 1.],
       ...,
       [1., 0., 0., ..., 0., 1., 1.],
       [1., 0., 0., ..., 0., 1., 1.],
       [1., 0., 0., ..., 0., 1., 1.]])

In [36]:
x_train=processed_data[:,:-1]
y_train=processed_data[:,-1]
y_train

array([0., 1., 1., 1., 0., 0., 1., 0., 1., 1., 1., 0., 1., 1., 1., 1., 0.,
       1., 1., 0., 0., 1., 1., 1., 0., 1., 1., 1., 1., 0., 0., 1., 1., 1.,
       1., 0., 0., 1., 0., 1., 1., 1., 1., 1., 1., 0., 1., 0., 0., 0., 0.,
       1., 1., 1., 0., 1., 0., 1., 1., 1., 1., 0., 0., 1., 1., 1., 1., 0.,
       1., 0., 1., 1., 1., 1., 0., 0., 0., 0., 1., 1., 1., 1., 1., 0., 1.,
       1., 0., 0., 1., 0., 0., 1., 1., 0., 1., 1., 1., 1., 1., 1., 0., 1.,
       1., 1., 0., 1., 1., 1., 1., 0., 1., 1., 1., 1., 0., 0., 1., 0., 1.,
       1., 1., 0., 1., 1., 1., 1., 1., 1., 1., 1., 0., 1., 0., 0., 1., 1.,
       1., 1., 1., 1., 0., 1., 1., 0., 0., 1., 1., 1., 1., 0., 1., 1., 1.,
       0., 0., 0., 1., 1., 1., 1., 1., 1., 1., 0., 1., 0., 1., 1., 1., 1.,
       0., 1., 0., 1., 0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0.,
       1., 1., 1., 1., 1., 0., 1., 0., 1., 1., 0., 0., 1., 1., 1., 1., 0.,
       1., 1., 0., 1., 0., 0., 1., 1., 1., 1., 1., 0., 1., 1., 0., 0., 1.,
       1., 1., 1., 1., 0., 1., 1., 0., 1., 1., 0., 1., 1., 1., 1., 0., 0.,
       1., 1., 0., 1., 0., 1., 1., 1., 1., 0., 1., 1., 1., 1., 1., 1., 0.,
       1., 1., 1., 1., 0., 1., 1., 0., 0., 1., 1., 1., 1., 0., 1., 0., 1.,
       1., 0., 1., 1., 1., 0., 1., 0., 1., 1., 1., 1., 0., 1., 0., 1., 1.,
       1., 1., 0., 1., 0., 0., 1., 1., 1., 0., 0., 1., 0., 1., 1., 1., 1.,
       1., 0., 0., 1., 0., 0., 1., 1., 1., 1., 1., 0., 1., 0., 1., 1., 1.,
       1., 1., 1., 1., 1., 0., 0., 1., 1., 1., 1., 1., 1., 0., 1., 1., 1.,
       0., 1., 1., 1., 1., 0., 1., 1., 0., 0., 1., 1., 1., 0., 1., 1., 0.,
       0., 1., 1., 1., 0., 1., 0., 1., 1., 1., 1., 0., 1., 0., 1., 1., 0.,
       0., 1., 1., 1., 0., 0., 1., 0., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 0., 1., 1., 1., 1., 1., 0., 0., 1., 1., 1., 1., 0., 0., 0., 0.,
       0., 1., 0., 1., 1., 0., 1., 1., 1., 0., 0., 1., 1., 0., 1., 1., 1.,
       1., 1., 0., 0., 1., 1., 1., 0., 0., 1., 1., 0., 1., 1., 1., 0., 1.,
       1., 0., 1., 0., 0., 1., 0., 1., 0., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 0., 1., 1., 1., 1., 1., 1., 0., 1., 1., 0., 1., 1., 1., 1., 0.,
       1., 1., 1., 1., 1., 1., 1., 0., 1., 0., 1., 1., 1., 1., 1.])

In [38]:
from imblearn.over_sampling import SMOTE
smote=SMOTE()

In [44]:
x_train_smote,y_train_smote=smote.fit_resample(x_train,y_train)

In [45]:
len(x_train_smote)

684

In [46]:
len(y_train_smote)

684

In [47]:
len(y_train)

684

In [49]:
from sklearn.svm import SVC
svclassifier = SVC()
svclassifier.fit(x_train_smote, y_train_smote)

SVC()

In [50]:
test_processed=preprocessor.transform(test)

In [52]:
x_test=test_processed[:,:-1]
y_test=test_processed[:,-1]
y_test

array([1., 1., 1., 1., 1., 1., 1., 1., 0., 0., 0., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0., 1., 1., 1., 1., 1., 1.,
       0., 0., 0., 1., 1., 0., 1., 1., 0., 1., 1., 1., 0., 0., 0., 0., 0.,
       0., 0., 0., 1., 0., 0., 1., 0., 1., 1., 0., 0., 1., 1., 1., 1., 1.,
       0., 0., 0., 1., 0., 0., 0., 1., 1., 0., 0., 1., 0., 1., 0., 0., 1.,
       1., 1., 0., 1., 0., 0., 0., 0., 1., 1., 1., 1., 1., 0., 1., 1., 1.,
       1., 1., 1., 0., 1., 0., 1., 1., 1., 0., 1., 1., 1., 1., 1., 0., 1.,
       1., 1., 1., 1.])

In [53]:
y_pred=svclassifier.predict(x_test)

In [55]:
from sklearn.metrics import classification_report,confusion_matrix
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

         0.0       0.10      0.02      0.04        43
         1.0       0.63      0.89      0.74        80

    accuracy                           0.59       123
   macro avg       0.36      0.46      0.39       123
weighted avg       0.44      0.59      0.49       123

In [56]:
#hyperparameters
from sklearn.model_selection import GridSearchCV
from itertools import product

param_grid_linear = {
    'C': [0.1, 5, 10, 15, 60, 70],
    'kernel' : ['linear'],
    'gamma' : ['scale', 'auto']
}
param_grid_rbf = {
    'C': [0.1, 5, 10, 15, 60, 70],
    'kernel' : ['rbf'],
    'gamma' : ['scale', 'auto']
}
param_grid_poly = {
    'C': [0.1, 5, 10, 15, 60, 70],
    'kernel' : ['poly'],
    'gamma' : ['scale', 'auto']
}

In [59]:
model_linear = SVC()
model_rbf = SVC()
model_poly = SVC()
model = SVC()

grid = GridSearchCV(model, param_grid=param_grid_rbf,refit=True,verbose=2,scoring='f1',cv=3)
grid.fit(x_train_smote, y_train_smote)

Fitting 3 folds for each of 12 candidates, totalling 36 fits
[CV] END .....................C=0.1, gamma=scale, kernel=rbf; total time=   0.2s
[CV] END .....................C=0.1, gamma=scale, kernel=rbf; total time=   0.1s
[CV] END .....................C=0.1, gamma=scale, kernel=rbf; total time=   0.1s
[CV] END ......................C=0.1, gamma=auto, kernel=rbf; total time=   0.1s
[CV] END ......................C=0.1, gamma=auto, kernel=rbf; total time=   0.1s
[CV] END ......................C=0.1, gamma=auto, kernel=rbf; total time=   0.1s
[CV] END .......................C=5, gamma=scale, kernel=rbf; total time=   0.1s
[CV] END .......................C=5, gamma=scale, kernel=rbf; total time=   0.1s
[CV] END .......................C=5, gamma=scale, kernel=rbf; total time=   0.1s
[CV] END ........................C=5, gamma=auto, kernel=rbf; total time=   0.1s
[CV] END ........................C=5, gamma=auto, kernel=rbf; total time=   0.1s
[CV] END ........................C=5, gamma=auto, kernel=rbf; total time=   0.1s
[CV] END ......................C=10, gamma=scale, kernel=rbf; total time=   0.2s
[CV] END ......................C=10, gamma=scale, kernel=rbf; total time=   0.2s
[CV] END ......................C=10, gamma=scale, kernel=rbf; total time=   0.1s
[CV] END .......................C=10, gamma=auto, kernel=rbf; total time=   0.1s
[CV] END .......................C=10, gamma=auto, kernel=rbf; total time=   0.0s
[CV] END .......................C=10, gamma=auto, kernel=rbf; total time=   0.0s
[CV] END ......................C=15, gamma=scale, kernel=rbf; total time=   0.0s
[CV] END ......................C=15, gamma=scale, kernel=rbf; total time=   0.0s
[CV] END ......................C=15, gamma=scale, kernel=rbf; total time=   0.0s
[CV] END .......................C=15, gamma=auto, kernel=rbf; total time=   0.0s
[CV] END .......................C=15, gamma=auto, kernel=rbf; total time=   0.0s
[CV] END .......................C=15, gamma=auto, kernel=rbf; total time=   0.0s
[CV] END ......................C=60, gamma=scale, kernel=rbf; total time=   0.0s
[CV] END ......................C=60, gamma=scale, kernel=rbf; total time=   0.0s
[CV] END ......................C=60, gamma=scale, kernel=rbf; total time=   0.0s
[CV] END .......................C=60, gamma=auto, kernel=rbf; total time=   0.0s
[CV] END .......................C=60, gamma=auto, kernel=rbf; total time=   0.0s
[CV] END .......................C=60, gamma=auto, kernel=rbf; total time=   0.0s
[CV] END ......................C=70, gamma=scale, kernel=rbf; total time=   0.0s
[CV] END ......................C=70, gamma=scale, kernel=rbf; total time=   0.0s
[CV] END ......................C=70, gamma=scale, kernel=rbf; total time=   0.0s
[CV] END .......................C=70, gamma=auto, kernel=rbf; total time=   0.0s
[CV] END .......................C=70, gamma=auto, kernel=rbf; total time=   0.0s
[CV] END .......................C=70, gamma=auto, kernel=rbf; total time=   0.0s

GridSearchCV(cv=3, estimator=SVC(),
             param_grid={'C': [0.1, 5, 10, 15, 60, 70],
                         'gamma': ['scale', 'auto'], 'kernel': ['rbf']},
             scoring='f1', verbose=2)

In [60]:
with open("model.pkl","wb") as f:
    pickle.dump(grid,f)

In [61]:
print(grid.best_params_)
print(grid.best_score_)

{'C': 5, 'gamma': 'auto', 'kernel': 'rbf'}
0.7668687950424996

In [63]:
svclassifier = SVC(C=10, gamma='auto', kernel='rbf')
svclassifier.fit(x_train_smote, y_train_smote)

SVC(C=10, gamma='auto')

In [64]:
y_hat=grid.predict(x_test)

In [65]:
print(classification_report(y_test,y_hat))

              precision    recall  f1-score   support

         0.0       0.69      0.47      0.56        43
         1.0       0.76      0.89      0.82        80

    accuracy                           0.74       123
   macro avg       0.72      0.68      0.69       123
weighted avg       0.73      0.74      0.73       123